#
# Copyright (c) 2015 Google, Inc
# Written by Simon Glass <sjg@chromium.org>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += led-uclass.o
obj-$(CONFIG_LEDS_AW2013) += leds_aw2013.o
obj-$(CONFIG_$(SPL_)LED_GPIO) += led_gpio.o
